[2025-04-23T23:17:43.668+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T23:17:43.685+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.predict manual__2025-04-23T23:15:42.842114+00:00 [queued]>
[2025-04-23T23:17:43.696+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.predict manual__2025-04-23T23:15:42.842114+00:00 [queued]>
[2025-04-23T23:17:43.697+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-23T23:17:43.710+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): predict> on 2025-04-23 23:15:42.842114+00:00
[2025-04-23T23:17:43.720+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3645) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T23:17:43.722+0000] {standard_task_runner.py:72} INFO - Started process 3648 to run task
[2025-04-23T23:17:43.720+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'predict', 'manual__2025-04-23T23:15:42.842114+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_train_predict.py', '--cfg-path', '/tmp/tmphoxjesba']
[2025-04-23T23:17:43.723+0000] {standard_task_runner.py:105} INFO - Job 307: Subtask predict
[2025-04-23T23:17:43.777+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_prediction.predict manual__2025-04-23T23:15:42.842114+00:00 [running]> on host d01273b1fd04
[2025-04-23T23:17:43.865+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T23:15:42.842114+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T23:15:42.842114+00:00'
[2025-04-23T23:17:43.868+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T23:17:43.880+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-23T23:17:43.882+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-23T23:17:43.883+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-23T23:17:43.884+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T23:18:09.748+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-23T23:18:09.835+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-23T23:18:09.837+0000] {connection.py:788} INFO - closed
[2025-04-23T23:18:09.882+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-04-23T23:18:10.040+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T23:18:10.057+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T23:18:10.058+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_price_prediction, task_id=predict, run_id=manual__2025-04-23T23:15:42.842114+00:00, execution_date=20250423T231542, start_date=20250423T231743, end_date=20250423T231810
[2025-04-23T23:18:10.104+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T23:18:10.126+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T23:18:10.130+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
