[2025-04-24T00:00:05.886+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T00:00:05.900+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T00:00:05.908+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T00:00:05.910+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-24T00:00:05.922+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-04-23 00:00:00+00:00
[2025-04-24T00:00:05.930+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '226_lab1_etl', 'load', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_etl.py', '--cfg-path', '/tmp/tmp08nfz6xz']
[2025-04-24T00:00:05.932+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5750) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T00:00:05.933+0000] {standard_task_runner.py:105} INFO - Job 321: Subtask load
[2025-04-24T00:00:05.934+0000] {standard_task_runner.py:72} INFO - Started process 5753 to run task
[2025-04-24T00:00:05.980+0000] {task_command.py:467} INFO - Running <TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [running]> on host d01273b1fd04
[2025-04-24T00:00:06.084+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='226_lab1_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T00:00:06.086+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T00:00:06.107+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-24T00:00:06.109+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T00:00:06.110+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T00:00:06.636+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T00:00:06.772+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T00:06:03.771+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T00:06:03.773+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T00:06:03.788+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T00:06:03.789+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=226_lab1_etl, task_id=load, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T000005, end_date=20250424T000603
[2025-04-24T00:06:03.840+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T00:06:03.856+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T00:06:03.860+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-24T19:00:04.631+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T19:00:04.650+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T19:00:04.663+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T19:00:04.665+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-24T19:00:04.681+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-04-23 00:00:00+00:00
[2025-04-24T19:00:04.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '226_lab1_etl', 'load', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_etl.py', '--cfg-path', '/tmp/tmpc1aujfhn']
[2025-04-24T19:00:04.694+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask load
[2025-04-24T19:00:04.696+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=907) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T19:00:04.698+0000] {standard_task_runner.py:72} INFO - Started process 914 to run task
[2025-04-24T19:00:04.760+0000] {task_command.py:467} INFO - Running <TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [running]> on host 463df1d38e6b
[2025-04-24T19:00:04.887+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='226_lab1_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T19:00:04.889+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T19:00:04.918+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-24T19:00:04.920+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T19:00:04.921+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T19:00:06.524+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T19:00:06.683+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T19:06:10.850+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T19:06:10.852+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T19:06:10.865+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T19:06:10.867+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=226_lab1_etl, task_id=load, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T190004, end_date=20250424T190610
[2025-04-24T19:06:10.932+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T19:06:10.948+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T19:06:10.952+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-24T19:59:42.245+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T19:59:42.268+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T19:59:42.283+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T19:59:42.284+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-24T19:59:42.304+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-04-23 00:00:00+00:00
[2025-04-24T19:59:42.315+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '226_lab1_etl', 'load', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_etl.py', '--cfg-path', '/tmp/tmpmivaiznr']
[2025-04-24T19:59:42.319+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask load
[2025-04-24T19:59:42.319+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=593) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T19:59:42.320+0000] {standard_task_runner.py:72} INFO - Started process 598 to run task
[2025-04-24T19:59:42.388+0000] {task_command.py:467} INFO - Running <TaskInstance: 226_lab1_etl.load scheduled__2025-04-23T00:00:00+00:00 [running]> on host 785c12b0fea3
[2025-04-24T19:59:42.505+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='226_lab1_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T19:59:42.507+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T19:59:42.529+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-24T19:59:42.531+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T19:59:42.532+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T19:59:43.809+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T19:59:43.923+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T20:05:50.353+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T20:05:50.356+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T20:05:50.370+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T20:05:50.372+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=226_lab1_etl, task_id=load, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T195942, end_date=20250424T200550
[2025-04-24T20:05:50.456+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T20:05:50.471+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T20:05:50.484+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
